### ISSUE TITLE
Exception in ConvertValueToNumericIfEnum

### ISSUE THREAD

**Issue by ondrasvoboda** [npgsql/EntityFramework6.Npgsql#126]
I'm getting Object reference not set to an instance of an object exception in 
```
   at System.Object.GetType()
   at Npgsql.NpgsqlServices.ConvertValueToNumericIfEnum(DbParameter parameter)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.SyncParameterProperties(EntityParameter entityParameter, DbParameter storeParameter, DbProviderServices storeProviderServices)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.PrepareEntityCommandBeforeExecution(EntityCommand entityCommand)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__c.MoveNext()
```
I think there is parameter.value != null check missing in NpgsqlServices.cs:63

This is connected to #105 and happens when parameter value is null.

**Comment by roji** [comment]
Can you please provide a code sample for when this happens?

**Comment by ondrasvoboda** [comment]
I've found out that this happens in combination with https://github.com/zzzprojects/EntityFramework.DynamicFilters I'm also using in my project. 

I have following filter setup in my DbContext
```
modelBuilder.Filter("RecordState", (TrackedEntity e) => e.RecordState, (MyContext ctx) => ctx.RecordStateFilterValue);
modelBuilder.EnableFilter("RecordState", (MyContext ctx) => ctx.RecordStateFilterEnabled);
```
I think dynamic enable/disable filter functionality (the second line in above code) is causing the troubles. It dynamically adds condition like this `OR (@DynamicFilterParam_000001 IS NOT NULL)` into the query with `DynamicFilterParam_000001` set to NULL when filter is enabled. Then it fails with above exception.

**Comment by roji** [comment]
Unfortunately we really don't have the time to take understand the interplay between this 3rd-party package and our EF6 provider (we're already not giving the EF6 provider enough attention...). The best way forward here would be to try to reproduce the problematic behavior without the DynamicFilters package.

**Comment by ondrasvoboda** [comment]
Thanks for fixing this.
