### ISSUE TITLE
Error Generating the Tables d

### ISSUE THREAD

**Issue by AndyZakk** [npgsql/EntityFramework6.Npgsql#130]
---------------------------
Microsoft Visual Studio
---------------------------
Encountered the following errors while processing the template 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\DBGen\SSDLToSQL10.tt: 

Line 59, Column 0: 'Running transformation: System.InvalidOperationException: The SSDL generated by the activity called 'CsdlToSsdlAndMslActivity' is not valid and has the following errors: 

The ADO.NET provider with invariant name 'Npgsql' is either not registered in the machine or application config file, or could not be loaded. See the inner exception for details.

   at Microsoft.Data.Entity.Design.DatabaseGeneration.EdmExtension.CreateAndValidateStoreItemCollection(String ssdl, Version targetFrameworkVersion, IDbDependencyResolver resolver, Boolean catchThrowNamingConflicts)

   at Microsoft.VisualStudio.TextTemplatingDA57C8B17B2A20E05842B8F66F5152D18D7CC68C2F6C97903ECF3233F7D60AC98695D38E5AE8A22074A2B7A00B8222BC6DD3690E0E1EAFD6FAF620D18FE2C023.GeneratedTextTransformation.get_Store() in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\Templates\Includes\GenerateTSQL.Utility.ttinclude:line 60

   at Microsoft.VisualStudio.TextTemplatingDA57C8B17B2A20E05842B8F66F5152D18D7CC68C2F6C97903ECF3233F7D60AC98695D38E5AE8A22074A2B7A00B8222BC6DD3690E0E1EAFD6FAF620D18FE2C023.GeneratedTextTransformation.TransformText() in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\DBGen\SSDLToSQL10.tt:line 84'

---------------------------
OK   
---------------------------
![Capture](https://user-images.githubusercontent.com/8595736/62080656-15253100-b21f-11e9-898d-aa0f3f32b0af.PNG)

**Comment by roji** [comment]
This seems to be an installation issue with Npgsql. Can you confirm you've properly installed the VSIX in Visual Studio and provide the exact versions for everything (the VSIX, VS...).

**Comment by roji** [comment]
Also, a small step-by-step list of what you've done to trigger this error would help, in additional to any related C# code.
