### ISSUE TITLE
Support for PostgreSQL functions when using Database First

### ISSUE THREAD

**Issue by Duy-KMS** [npgsql/EntityFramework6.Npgsql#150]
I have an error while calling a function that added to EDMX by using Database First, I also make a pull request for fixing this issue

Value does not fall within the expected range.

```C#
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.EntityClient.EntityCommand.CreateCommandDefinition()
   at System.Data.Entity.Core.EntityClient.EntityCommand.TryGetEntityCommandDefinitionFromQueryCache(EntityCommandDefinition& entityCommandDefinition)
   at System.Data.Entity.Core.EntityClient.EntityCommand.GetCommandDefinition()
   at System.Data.Entity.Core.Objects.ObjectContext.CreateFunctionObjectResult[TElement](EntityCommand entityCommand, ReadOnlyCollection`1 entitySets, EdmType[] edmTypes, ExecutionOptions executionOptions)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass161_0`1.<ExecuteFunction>b__1()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass161_0`1.<ExecuteFunction>b__0()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction[TElement](String functionName, ExecutionOptions executionOptions, ObjectParameter[] parameters)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction[TElement](String functionName, MergeOption mergeOption, ObjectParameter[] parameters)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteFunction[TElement](String functionName, ObjectParameter[] parameters)```

**Comment by Duy-KMS** [comment]
The Pull Request for this issue:
https://github.com/npgsql/EntityFramework6.Npgsql/pull/151

**Comment by trietphamnm** [comment]
@roji This is a road blocking issue of using pg functions via EDMX mapping. The provided PR seems to be pretty simple. It would be great if you could spend a few minutes looking at it.

**Comment by roji** [comment]
The PR looks OK to me, if @Emill can approve it I can merge and release.

**Comment by Emill** [comment]
Looks fine!

**Comment by trietphamnm** [comment]
Thanks for this awesome tool, @roji @Emill
