### ISSUE TITLE
Is EF6' AlterTableAnnotation supported?

### ISSUE THREAD

**Issue by roji** [npgsql/EntityFramework6.Npgsql#33]
_From @tiwariarvin on April 8, 2016 4:59_

Hi - I get error copied below, when I run an "AlterTableAnnotation" migratio. Can someone please confirm is that is supported in this Postgres driver (or) in PostGres? If it is, how can fix this error?

"Unhandled MigrationOperation AlterTableOperation in NpgsqlMigrationSqlGenerator"

Below is the stack trace -
Stack trace on PM -
Applying explicit migration: 201604041142031_test.
System.NotImplementedException: Unhandled MigrationOperation AlterTableOperation in NpgsqlMigrationSqlGenerator
at Npgsql.NpgsqlMigrationSqlGenerator.Convert(IEnumerable1 operations) at Npgsql.NpgsqlMigrationSqlGenerator.Generate(IEnumerable1 migrationOperations, String providerManifestToken)
at System.Data.Entity.Migrations.DbMigrator.GenerateStatements(IList1 operations, String migrationId) at System.Data.Entity.Migrations.Infrastructure.MigratorBase.GenerateStatements(IList1 operations, String migrationId)
at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable1 operations, IEnumerable1 systemOperations, Boolean downgrading, Boolean auto)
at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable1 pendingMigrations, String targetMigrationId, String lastMigrationId) at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable1 pendingMigrations, String targetMigrationId, String lastMigrationId)
at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.b__b()
at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)

_Copied from original issue: npgsql/npgsql#1020_

**Comment by roji** [comment]
It seems Npgsql's EF6 provider indeed doesn't implement AlterTableOperation. This shouldn't be very hard to implement but I have other things on my plate at the moment, marking as up for grabs for now.

**Comment by roji** [comment]
Can you please post the exact operation you are trying to achieve and which triggered this exception?

**Comment by roji** [comment]
_From @tiwariarvin on April 12, 2016 11:1_

Sure Roji, And agree "AlterTableAnnotation" is processed differently by different drivers out there.

As requested, please find below copied migration which resulted into this exception. Additionally, if you wish I can contribute possibly by the end of next week to get this resolved.

AlterTableAnnotations(
                "someschema.sometable",
                c => new
                    {
                        //deleted code here
                    },
                annotations: new Dictionary<string, AnnotationValues>
                {
                    { 
                        "DynamicFilter_Annoucement_IsDeleted",
                        new AnnotationValues(oldValue: null, newValue: "EntityFramework.DynamicFilters.DynamicFilterDefinition")
                    },
                });

Thanks

**Comment by Imbasaur** [comment]
Any news on this?

**Comment by sylfree9999** [comment]
Any update??

**Comment by MichaelFurmedge** [comment]
Was this ever updated?  I'm coming across this today.

**Comment by roji** [comment]
There hasn't been enough time (and requests) for this, and I personally definitely won't be able to work on it anytime soon. The issue is marked up for grabs so anyone is welcome to take a stab at it.
