### ISSUE TITLE
EF6 update-database -script fails

### ISSUE THREAD

**Issue by cland410** [npgsql/EntityFramework6.Npgsql#64]
I am using EntityFramework 6.1.3, EntityFramework6.Npgsql 3.1.1, Npgsql 3.2.0

When I use "update-database", the connected Postgres database gets updated properly. When I try to generate migration script using "update-database -script -sourcemigration:$InitialDatabase" I get the below message in the Package Manager Console. 

System.NullReferenceException: Object reference not set to an instance of an object.
   at Npgsql.NpgsqlMigrationSqlGenerator.Convert(IEnumerable`1 operations)
   at Npgsql.NpgsqlMigrationSqlGenerator.Convert(IEnumerable`1 operations)
   at Npgsql.NpgsqlMigrationSqlGenerator.Generate(IEnumerable`1 migrationOperations, String providerManifestToken)
   at System.Data.Entity.Migrations.DbMigrator.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorScriptingDecorator.ScriptUpdate(String sourceMigration, String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScriptUpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScriptUpdate(String sourceMigration, String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Object reference not set to an instance of an object.

**Comment by BrunoCanto** [comment]
I'm getting same error.
EntityFramework 6.1.3, EntityFramework6.Npgsql 3.1.1, Npgsql 3.2.5
