### ISSUE TITLE
Could not load type 'Npgsql.NpgsqlError' from assembly 'Npgsql, Version=3.2.6.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'

### ISSUE THREAD

**Issue by aammfe** [npgsql/EntityFramework6.Npgsql#86]
Created Simple Console Application.

This is my package configuration.
`<packages>
  <package id="EntityFramework" version="6.0.0" targetFramework="net461" />
  <package id="Npgsql" version="2.2.7" targetFramework="net461" />
  <package id="Npgsql.EntityFramework" version="2.2.7" targetFramework="net461" />
</packages>
`

This is my AppConfig

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>

  <connectionStrings>
    <add name="MonkeyFist" connectionString="****" providerName="Npgsql" />
  </connectionStrings>

  
 
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  
  
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="Npgsql" type="Npgsql.NpgsqlServices, Npgsql.EntityFramework" />
    </providers>
  </entityFramework>

  <system.data>
    <DbProviderFactories>
      <remove invariant="Npgsql" />
      <add name="Npgsql Data Provider" invariant="Npgsql" description=".Net Data Provider for PostgreSQL" type="Npgsql.NpgsqlFactory, Npgsql, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7" support="FF" />
    </DbProviderFactories>
  </system.data>
  
  
</configuration>`

Every thing work fine until I update Database.

Update-Database

Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [201801101608526_init].
Applying explicit migration: 201801101608526_init.
System.TypeLoadException: Could not load type 'Npgsql.NpgsqlError' from assembly 'Npgsql, Version=3.2.6.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)

Could not load type 'Npgsql.NpgsqlError' from assembly 'Npgsql, Version=3.2.6.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.

**Comment by roji** [comment]
You seem to have a version mismatch: the error complains about not finding Npgsql.NpgsqlError in Npgsql.dll version 3.2.6, while your package.config shows 2.2.7. NpgsqlError is indeed an old type that existed in 2.2.7 but no longer exists. Take a look at the versions you're specifying and make sure they're aligned. I also recommend you upgrade to 3.2, since 2.2 is really ancient.

**Comment by hajderr** [comment]
Can confirm this was due to version mismatch between EFCore and Npgsql
